// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type LandingPageDocumentDataSlicesSlice =
  | FeaturedSectionSlice
  | HeroSectionSlice;

/**
 * Content for Landing page documents
 */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *Landing page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Landing page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Item in *Navbar → Menu*
 */
export interface NavbarDocumentDataMenuItem {
  /**
   * link field in *Navbar → Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Navbar → Buttons*
 */
export interface NavbarDocumentDataButtonsItem {
  /**
   * link field in *Navbar → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Varient field in *Navbar → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: ghost
   * - **API ID Path**: navbar.buttons[].varient
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  varient: prismic.SelectField<
    "ghost" | "primary" | "secondary" | "outline",
    "filled"
  >;
}

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * Logo field in *Navbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Menu field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu: prismic.GroupField<Simplify<NavbarDocumentDataMenuItem>>;

  /**
   * Buttons field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.buttons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<NavbarDocumentDataButtonsItem>>;
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

export type AllDocumentTypes = LandingPageDocument | NavbarDocument;

/**
 * Item in *FeaturedSection → Default → Primary → Buttons*
 */
export interface FeaturedSectionSliceDefaultPrimaryButtonItem {
  /**
   * Link field in *FeaturedSection → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.button[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "ghost" | "primary" | "secondary" | "outline"
  >;
}

/**
 * Primary content in *FeaturedSection → Default → Primary*
 */
export interface FeaturedSectionSliceDefaultPrimary {
  /**
   * Image field in *FeaturedSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Label field in *FeaturedSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Date field in *FeaturedSection → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Title field in *FeaturedSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *FeaturedSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Buttons field in *FeaturedSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.button[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  button: prismic.GroupField<
    Simplify<FeaturedSectionSliceDefaultPrimaryButtonItem>
  >;
}

/**
 * Default variation for FeaturedSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedSection*
 */
type FeaturedSectionSliceVariation = FeaturedSectionSliceDefault;

/**
 * FeaturedSection Shared Slice
 *
 * - **API ID**: `featured_section`
 * - **Description**: FeaturedSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedSectionSlice = prismic.SharedSlice<
  "featured_section",
  FeaturedSectionSliceVariation
>;

/**
 * Item in *HeroSection → Default → Primary → Buttons*
 */
export interface HeroSectionSliceDefaultPrimaryButtonsItem {
  /**
   * Link field in *HeroSection → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "ghost" | "primary" | "Secondary" | "outline"
  >;
}

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * HeroBgImg field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.herobgimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  herobgimg: prismic.ImageField<never>;

  /**
   * HeroFhImg field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.herofhimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  herofhimg: prismic.ImageField<never>;

  /**
   * Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Buttons field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<
    Simplify<HeroSectionSliceDefaultPrimaryButtonsItem>
  >;

  /**
   * Label field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataMenuItem,
      NavbarDocumentDataButtonsItem,
      AllDocumentTypes,
      FeaturedSectionSlice,
      FeaturedSectionSliceDefaultPrimaryButtonItem,
      FeaturedSectionSliceDefaultPrimary,
      FeaturedSectionSliceVariation,
      FeaturedSectionSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimaryButtonsItem,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
    };
  }
}
