// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_section: dynamic(() => import("./FeaturedSection")),
  hero_section: dynamic(() => import("./HeroSection")),
};
